import { IQuestion, IQuiz } from './quiz.js';

const questionsEasy : IQuestion[] = [ 
    {
        id: 1,
        expression: "2 + 3",
        correctAnswer: 5,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 2,
        expression: "7 * (2 + 3)",
        correctAnswer: 35,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 3,
        expression: "(2 + 4) : 2 + 1",
        correctAnswer: 4,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 4,
        expression: "(10 - 4) * 3 - 2",
        correctAnswer: 16,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 5,
        expression: "(12 / 4) * (12 / 3)",
        correctAnswer: 12,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 6,
        expression: "2 * 5 - 1",
        correctAnswer: 9,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 7,
        expression: "(10 - 2) / 4 + 1",
        correctAnswer: 3,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 8,
        expression: "(15 - 3) : 4 + 1",
        correctAnswer: 4,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 9,
        expression: "7 + 3 + 1 * 4",
        correctAnswer: 14,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 10,
        expression: "3 * 7 - 12",
        correctAnswer: 9,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
]

const questionsMedium : IQuestion[] = [ 
    {
        id: 1,
        expression: "8 * 7",
        correctAnswer: 56,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 2,
        expression: "7 * (8 + 3) - 8",
        correctAnswer: 69,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 3,
        expression: "(12 * 4) / 8 + 1",
        correctAnswer: 7,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 4,
        expression: "((2 ^ 10) - 24) / 10 - 1",
        correctAnswer: 99,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 5,
        expression: "(7 * 8) - (6 * 7)",
        correctAnswer: 21,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 6,
        expression: "(3 ^ 3) - (2 ^ 2) + (1 ^ 1)",
        correctAnswer: 24,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 7,
        expression: "(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10) / 5",
        correctAnswer: 11,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
]


const questionsHard : IQuestion[] = [ 
    {
        id: 1,
        expression: "(2!)/(1!) + (3!)/(2!) + ... + (10!)/(9!)",
        correctAnswer: 54,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 2,
        expression: "(99 - 1) * (98 - 2) * (97 - 3) * ... * (1 - 99)",
        correctAnswer: 0,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 3,
        expression: "(1 + 2 + 3 + ... + 100)",
        correctAnswer: 5050,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 4,
        expression: "43 * (1/(1 * 2) + 1/(2 * 3) + ... + 1/(42 * 43))",
        correctAnswer: 42,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
    {
        id: 5,
        expression: "(1 + 3 + 5 + ... + 49) - (5^4)",
        correctAnswer: 0,
        playerAnswer: undefined,
        time: 0,
        penalty: 0,
        correct: false,
    },
]

export const quizEasy : IQuiz= {
    name: "Łatwy",
    introduction: "Liczyć każdy może...",
    questions: questionsEasy,
    currentQuestion: undefined,
    result: 0,
} 

export const quizMedium : IQuiz= {
    name: "Średni",
    introduction: "Spytacie jak trudny jest ten quiz. Nie jest trudny.\nCo prawda nie jest też łatwy, można powiedzieć że jest średni.",
    questions: questionsMedium,
    currentQuestion: undefined,
    result: 0,
} 

export const quizHard : IQuiz= {
    name: "Trudny",
    introduction: "Ciężkie zadania, na ciężkie czasy",
    questions: questionsHard,
    currentQuestion: undefined,
    result: 0,
} 